version: '3'

services:
  consul:
    image: 'consul:0.8.5'
    hostname: consul-server
    ports:
      - "8500:8500"
    environment:
     - CONSUL_ALLOW_PRIVILEGED_PORTS=true
    command: agent -server -bootstrap -bind=172.30.0.2 -client=0.0.0.0 -ui -dns-port=53 -recursor=8.8.8.8
    networks:
      webapp_net:
        ipv4_address: 172.30.0.2
  registrator:
    image: 'gliderlabs/registrator'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal consul://172.30.0.2:8500
    depends_on:
      - consul
    networks:
      webapp_net:
  mysql:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/data:/docker-entrypoint-initdb.d
    networks:
      webapp_net:
    dns:
      - 172.30.0.2
  webapp:
    build: ./webapp/
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      webapp_net:
    dns:
      - 172.30.0.2
networks:
    webapp_net:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 172.30.0.0/24
